### ISSUE TITLE
JSONException: Value <!-- 

### ISSUE THREAD

**Issue by romansolo** [queueit/android-webui-sdk#1]
Sometimes the app is crashing with the following logs

`Fatal Exception: java.lang.RuntimeException: org.json.JSONException: Value <!-- of type java.lang.String cannot be converted to JSONObject
       at com.queue_it.androidsdk.QueueService$1.onResponse(QueueService.java:115)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by org.json.JSONException: Value <!-- of type java.lang.String cannot be converted to JSONObject
       at org.json.JSON.typeMismatch(JSON.java:111)
       at org.json.JSONObject.<init>(JSONObject.java:160)
       at org.json.JSONObject.<init>(JSONObject.java:173)
       at com.newrelic.agent.android.instrumentation.JSONObjectInstrumentation.init(JSONObjectInstrumentation.java:22)
       at com.queue_it.androidsdk.QueueService$1.onResponse(QueueService.java:102)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

Seems like that HTML is coming instead of JSON in the response

**Comment by mbp** [comment]
Could you provide me with the parameters you passed to QueueITEngine (CustomerId and EventId) and the time that this occured?

You are also welcome to e-mail me at mope@queue-it.com
